AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-world
  Sample SAM Template for hello-world

Parameters:
  StageName:
    Type: String
    Default: poc
    Description: (Required) Enter poc, dev, uat, prod. Default is poc.
    AllowedValues:
      - poc
      - dev
      - uat
      - prod

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,x-oauth-config-provider,Authorization,X-Amz-Date'"
      AllowOrigin: "'*'"
      MaxAge: "'300'"
      AllowCredentials: false

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: !Ref StageName
      Auth:
        DefaultAuthorizer: MyCognitoAuth # OPTIONAL
        Authorizers:
          MyCognitoAuth:
            UserPoolArn:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello/'
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  RestApi:
    Description: 'API Gateway endpoint URL for Staging stage for Hello World function'
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello/'
  RestApi:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref RestApi
    Export:
      Name: RestApi-RestApiId
  RestApiRootResourceId:
    Value: !GetAtt RestApi.RootResourceId
    Export:
      Name: RestApi-RootResourceId

